// Liste des proclamateurs du groupe avec leurs statuts
export const initialData = [
  {
    name: "BECHOU Jérémy",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "BECHOU Ombeline",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "BECUWE Céline",
    auxiliar: false,
    permanent: true,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "BECUWE Clémence",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "BECUWE Emelyne",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "BECUWE Romane",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "BECUWE Sébastien",
    auxiliar: false,
    permanent: true,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "BELHOMME Annie",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "BEGERT Paulette",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "COUDRET Roland",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "ERNWEIN Béatrice",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "ERNWEIN Pierre",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "FRADE Fahima",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "FRADE José",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "HUMBERT Christian",
    auxiliar: false,
    permanent: true,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "HUMBERT Véronique",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "KALCK Francis",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "LE PIEZ Catherine",
    auxiliar: false,
    permanent: true,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "LE PIEZ Patrick",
    auxiliar: false,
    permanent: true,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "MAETZ Marie-Thérèse",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "SELVA Agnès",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "WERNERT Cyrielle",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "WERNERT Isabelle",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
  {
    name: "WERNERT Serge",
    auxiliar: false,
    permanent: false,
    worked: false,
    bibleCourses: "",
    remarks: "",
  },
];

// Liste des conducteurs (données distinctes des proclamateurs)
export const CONDUCTEURS = [
  "Sébastien BECUWE",
  "Pascal GRECO",
  "Christian HUMBERT",
  "Michaël JACQUOT",
  "Patrick LE PIEZ",
  "Gérard RAETH",
  "Victor TAHAR",
  "Jean-Marc WERNERT",
];

export const GROUP_TITLE = "Activité du Groupe";

// Helper : extrait uniquement les noms des proclamateurs
export const PROCLAMATEURS = initialData.map((p) => p.name);
